package com.tresors.vue;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Nicolas Sagon on 25/11/2014.
 */
public class VuePlateau extends JFrame {

    private JPanel mainPanel;
    private PlateauPanel plateauPanel;
    private JMenuBar menuBar;
    private JMenu file;
    private JMenuItem menuItemFileSave;
    private JMenuItem menuItemFileLoad;
    private JMenuItem menuItemFileExit;
    private JPanel panelScore;
    private JLabel labelJoueur1;
    private JPanel panelAction;
    private JButton buttonAction1;
    private JButton buttonAction2;
    private JLabel labelAction;


    public VuePlateau() {
        super("Les trésors de Java");

        menuBar = new JMenuBar();
        file = new JMenu("File");
        menuItemFileSave = new JMenuItem("Sauvegarder");
        menuItemFileLoad = new JMenuItem("Charger");
        menuItemFileExit = new JMenuItem("Quitter");

        file.add(menuItemFileSave);
        file.add(menuItemFileLoad);
        file.add(menuItemFileExit);

        menuItemFileExit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        menuBar.add(file);

        this.setJMenuBar(menuBar);

        panelScore = new JPanel();
        panelScore.setLayout(new FlowLayout());

        labelJoueur1 = new JLabel("Joueur 1 : LOL");
        panelScore.add(labelJoueur1);

        plateauPanel = new PlateauPanel();
        mainPanel.setLayout(new BorderLayout());

        panelAction = new JPanel();
        panelAction.setLayout(new BoxLayout(panelAction, BoxLayout.Y_AXIS));

        buttonAction1 = new JButton("Attaquer");
        buttonAction2 = new JButton("Réparer");
        labelAction = new JLabel("1");

        panelAction.add(labelAction, Component.CENTER_ALIGNMENT);
        panelAction.add(buttonAction1, Component.CENTER_ALIGNMENT);
        panelAction.add(buttonAction2, Component.CENTER_ALIGNMENT);

        mainPanel.add(plateauPanel, BorderLayout.CENTER);
        mainPanel.add(panelScore, BorderLayout.PAGE_START);
        mainPanel.add(panelAction, BorderLayout.LINE_END);
        add(mainPanel, BorderLayout.CENTER);



        pack();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        setSize((int) tk.getScreenSize().getWidth(), (int) tk.getScreenSize().getHeight());
        this.setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panel1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
